repos:
- repo: local
  hooks:
  - id: update-requirements-txt
    name: update-requirements-txt
    description: 'Generate requirements.txt based on poetry.lock'
    entry: poetry
    args: [export, --format, requirements.txt, --output, requirements.txt]
    language: system
    pass_filenames: false
